#!/bin/sh

#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright The DBT-5 Authors
#

while getopts "d:p:" OPT; do
	case ${OPT} in
	d)
		DBT5DBNAME=${OPTARG}
		;;
	p)
		PORT=${OPTARG}
		;;
	*)
		;;
	esac
done

if [ -z "${DBT5DBNAME}" ]; then
	echo "DBT5DBNAME not defined."
	exit 1
fi

if [ -n "${PORT}" ]; then
	PORTOPT="-p ${PORT}"
fi

dropdb "${PORTOPT}" "${DBT5DBNAME}" || exit 1
