#!/bin/sh

# Build a Docker image with the DBT-5 Brokerage House.

which docker > /dev/null 2>&1
if [ $? -ne 0 ]; then
	echo "docker not in path"
	exit 1
fi

PGVERSION=14.2

if [ $# -ge 1 ]; then
	PGVERSION=$1
else
	which jq > /dev/null 2>&1
	if [ $? -eq 0 ]; then
		PGORG="https://www.postgresql.org/versions.json"
		PGVERSION=$(curl -s $PGORG | jq -r 'sort | .[] | "\(.major).\(.latestMinor)"' | tail -n 1)
	fi
fi

echo "Using PostgreSQL Major Version $PGVERSION"

TOPDIR=`dirname $0`

# Use the return code from `docker inspect` to determine if the docker image
# needs to be created.
docker inspect dbt5-base > /dev/null
if [ $? -ne 0 ]; then
	${TOPDIR}/prepare-image || exit 1
fi

TOPDIR="${TOPDIR}/.."
docker build -t dbt5-driver \
		--build-arg PGVERSION=$PGVERSION \
		-f Dockerfile.common $TOPDIR
if [ $? -ne 0 ]; then
	echo "usage: $0 [DBMSVER]"
	echo
	exit 1
fi
