#!/bin/sh

# Build a Docker image with the DBT-5 Brokerage House.

if ! which docker > /dev/null 2>&1; then
	echo "docker not in path"
	exit 1
fi

PGVERSION=14.2

if [ $# -ge 1 ]; then
	PGVERSION=$1
else
	if which jq > /dev/null 2>&1; then
		PGORG="https://www.postgresql.org/versions.json"
		PGVERSION=$(curl -s "${PGORG}" \
				| jq -r 'sort | .[] | "\(.major).\(.latestMinor)"' \
				| tail -n 1)
	fi
fi

echo "Using PostgreSQL Major Version $PGVERSION"

TOPDIR=$(dirname "$0")

# Use the return code from `docker inspect` to determine if the docker image
# needs to be created.
if ! docker inspect dbt5-base > /dev/null; then
	"${TOPDIR}"/prepare-image || exit 1
fi

TOPDIR="${TOPDIR}"/..
if ! docker build -t dbt5-driver \
		--build-arg PGVERSION="${PGVERSION}" \
		-f Dockerfile.common "${TOPDIR}"; then
	echo "usage: $0 [DBMSVER]"
	echo
	exit 1
fi
