#!/bin/sh

# Build the entire test kit, except any database server side specific code.

if ! which docker > /dev/null 2>&1; then
	echo "docker not in path"
	exit 1
fi

DOCKER_DIR=$(dirname "$0")
DOCKER_DIR=$(readlink -f "${DOCKER_DIR}")

DOCKER_TAG="dbt5-driver"

DBT5_PATH="/usr/local/src/dbt5"

if [ "${VERBOSE}" = "" ]; then
	VERBOSE=0
fi

docker run --rm -v "${DOCKER_DIR}"/..:"${DBT5_PATH}":rw -w ${DBT5_PATH} \
		-e PKG_CONFIG_PATH="/usr/lib/pkgconfig" -e VERBOSE="${VERBOSE}" \
		-u "$(id -u)":"$(id -g)" ${DOCKER_TAG} \
		bash -c 'make clean; make debug' \
		|| exit 1
