#!/bin/sh

PGVERSION=14.2

# Build the entire test kit, except any database server side specific code.

which docker > /dev/null 2>&1
if [ $? -ne 0 ]; then
	echo "docker not in path"
	exit 1
fi

DOCKER_DIR=`dirname $0`
DOCKER_DIR=`readlink -f $DOCKER_DIR`

DOCKER_TAG="dbt5-driver"
UID=`id -u`
GID=`id -g`

DBT5_PATH="/usr/local/src/dbt5"

if [ $# -eq 0 ]; then
	which jq > /dev/null 2>&1
	if [ $? -ne 0 ]; then
		echo "install jq to automatically use the latest postgres version"
		echo "defaulting to version $PGVERSION"
	else
		PGORG="https://www.postgresql.org/versions.json"
		PGVERSION=$(curl -s $PGORG | jq -r 'sort | .[] | "\(.major).\(.latestMinor)"' | tail -n 1)
	fi
fi

if [ ! "x${VERBOSE}" = "x" ]; then
	VERBOSE_FLAG="-e VERBOSE=$VERBOSE"
fi

docker run --rm -v ${DOCKER_DIR}/..:${DBT5_PATH}:rw -w $DBT5_PATH \
		-e PKG_CONFIG_PATH="/usr/lib/pkgconfig" $VERBOSE_FLAG \
		-u ${UID}:${GID} $DOCKER_TAG \
		bash -c 'make -f Makefile.cmake clean; make -f Makefile.cmake debug' \
		|| exit 1
