#!/bin/sh

if [ -n "${ENGINE:-}" ]; then
	CONTAINER_CMD="${ENGINE}"
elif command -v podman > /dev/null 2>&1; then
	CONTAINER_CMD="podman"
elif command -v docker > /dev/null 2>&1; then
	CONTAINER_CMD="docker"
else
	echo "podman or docker is not in your path"
	exit 1
fi

CONTAINER_DIR="$(dirname "$(realpath "${0}")")"
CONTAINER_TAG="dbt5-appimage"
CONTAINERFILE="appimage/Containerfile.appimage"

ARCH="$(uname -m)"

if [ "${ARCH}" = "arm64" ]; then
	ARCH="aarch64"
fi

if [ "${CONTAINER_CMD}" = "podman" ]; then
	ISOLATION_ARG="--isolation=chroot"
else
	ISOLATION_ARG=""
fi

cd "$CONTAINER_DIR/.." && \
		${CONTAINER_CMD} build \
				${ISOLATION_ARG} \
				--build-arg ARCH="${ARCH}" \
				-t $CONTAINER_TAG \
				-f ${CONTAINERFILE} \
				.
