#!/bin/sh

if ! which podman > /dev/null 2>&1; then
	echo "podman is not in your path"
	exit 1
fi

CONTAINER_DIR="$(dirname "$(realpath "${0}")")"
CONTAINER_TAG="dbt5-appimage"
TARGET="appimage"

# Use the return code from `podman inspect` to determine if the container image
# needs to be created.
if ! podman inspect ${CONTAINER_TAG} > /dev/null 2>&1; then
	"${CONTAINER_DIR}/build-appimage-container" || exit 1
fi

podman run \
		--rm \
		--user "$(id -u):$(id -u)" \
		--userns=keep-id \
		-v "${CONTAINER_DIR}/..:/usr/local/src/dbt5:rw,Z" \
		--env EGEN="${EGEN}" \
		--env PKG_CONFIG_PATH="/usr/lib/pkgconfig" \
		-w /usr/local/src/dbt5 \
		$CONTAINER_TAG \
		make -f Makefile.cmake ${TARGET}
